// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

// NOTE: Bookerly and OpenDyslexic fonts have been removed to save space
// Only NotoSans (with Greek support) and Ubuntu UI fonts remain

#define NOTOSANS_12_FONT_ID (-1559651934)
#define NOTOSANS_14_FONT_ID (-1014561631)
#define NOTOSANS_16_FONT_ID (-1422711852)
#define NOTOSANS_18_FONT_ID (1237754772)
#define UI_10_FONT_ID (-1246724383)
#define UI_12_FONT_ID (-359249323)
#define SMALL_FONT_ID (1073217904)
